import { Outfit } from "next/font/google";
import "./globals.css";
import Navbar from "@/component/Navbar";
import Footer from "@/component/Footer";

const outfitFonts = Outfit({
  variable: "--font-outfit-sans",
  subsets: ["latin"],
});



export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${outfitFonts.className}  h-full antialiased`}
    >
      <body>
        <Navbar/>
        <main className="container m-auto my-10">
          {children}
        </main>
        <Footer></Footer>
        </body>
    </html>
  );
}
